ruby:
  enabled: true
  config_file: .rubocop.yml
haml:
  enabled: true
  config_file: .haml-lint.yml
#eslint:
#  enabled: true
#  config_file: .eslintrc.js
sass-lint:
  enabled: true
  config_file: .sass-lint.yml
